version: '3.8'

services:
  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: taskDB
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Сервис для Spring Boot приложения
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskDB
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      APP_PASSWORD: ${APP_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db  # Убедитесь, что база данных загружена до запуска приложения


volumes:
  postgres-data:
