version: '3.8'

services:
  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: taskDB
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"  # Пробрасываем внешний порт 5433 на внутренний 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Сервис для Spring Boot приложения
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskDB  # База данных по-прежнему использует внутренний порт 5432
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}  # Используем переменные окружения
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}  # Используем переменные окружения
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}  # Секретный ключ для JWT
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}  # Email для отправки сообщений
      APP_PASSWORD: ${APP_PASSWORD}  # Пароль для почты
    env_file:
      - .env  # Подключаем .env файл с секретами
    depends_on:
      - db  # Указываем, что приложение зависит от базы данных
    networks:
      - app-network

# Сетевое подключение для обмена данными между контейнерами
networks:
  app-network:
    driver: bridge

# Объем для хранения данных PostgreSQL
volumes:
  postgres-data:
    driver: local